# Generated by Django 4.1.2 on 2023-03-01 05:21

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phoneNumber', models.IntegerField(max_length=200, null=True)),
                ('profilePicture', pyuploadcare.dj.models.ImageField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ('firstName',),
            },
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='occassionalcakes',
            name='category',
        ),
        migrations.DeleteModel(
            name='WeddingCakes',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='OccassionalCakes',
        ),
    ]
